export const brandsData = [
    {id: 1, category: "basketball", brands: [
            {id: 1, value: 'nike', label: 'Nike'},
            {id: 2, value: 'adidas', label: 'Adidas'},
            {id: 3, value: 'puma', label: 'Puma'},
            {id: 4, value: 'jordan', label: 'Jordan'},
            {id: 5, value: 'underArmour', label: 'Under Armour'},
            {id: 6, value: 'convers', label: 'Convers'},
            {id: 7, value: 'reebok', label: 'Reebok'},
            {id: 8, value: 'anta', label: 'Anta'},
            {id: 9, value: 'li-ning', label: 'Li-ning'},
            {id: 9, value: 'newBalance', label: 'New Balance'},
            {id: 10, value: 'asics', label: 'Asics'},
            {id: 9, value: 'other', label: 'other'},
        ]},
    {id: 2, category: "street", brands: [
            {id: 1, value: 'nike', label: 'Nike'},
            {id: 2, value: 'adidas', label: 'Adidas'},
            {id: 3, value: 'puma', label: 'Puma'},
            {id: 4, value: 'jordan', label: 'Jordan'},
            {id: 5, value: 'underArmour', label: 'Under Armour'},
            {id: 6, value: 'convers', label: 'Convers'},
            {id: 7, value: 'reebok', label: 'Reebok'},
            {id: 8, value: 'anta', label: 'Anta'},
            {id: 9, value: 'li-ning', label: 'Li-ning'},
            {id: 9, value: 'newBalance', label: 'New Balance'},
            {id: 10, value: 'asics', label: 'Asics'},
            {id: 9, value: 'bape', label: 'Bape'},
            {id: 9, value: 'amiri', label: 'Amiri'},
            {id: 9, value: 'rickOwens', label: 'Rick Owens'},
            {id: 9, value: 'other', label: 'other'},
        ]},
    {id: 3, category: "premium", brands: [
            {id: 1, value: 'lv', label: 'LV'},
            {id: 2, value: 'gucci', label: 'Gucci'},
            {id: 3, value: 'dior', label: 'Dior'},
            {id: 4, value: 'balenciaga', label: 'Balenciaga'},
            {id: 5, value: 'prada', label: 'Prada'},
            {id: 9, value: 'other', label: 'other'},
             ]},
    {id: 3, category: "other", brands: [
            {id: 1, value: 'nike', label: 'Nike'},
            {id: 2, value: 'adidas', label: 'Adidas'},
            {id: 3, value: 'puma', label: 'Puma'},
            {id: 4, value: 'jordan', label: 'Jordan'},
            {id: 5, value: 'underArmour', label: 'Under Armour'},
            {id: 6, value: 'convers', label: 'Convers'},
            {id: 7, value: 'reebok', label: 'Reebok'},
            {id: 8, value: 'anta', label: 'Anta'},
            {id: 9, value: 'li-ning', label: 'Li-ning'},
            {id: 9, value: 'newBalance', label: 'New Balance'},
            {id: 10, value: 'asics', label: 'Asics'},
            {id: 9, value: 'bape', label: 'Bape'},
            {id: 9, value: 'amiri', label: 'Amiri'},
            {id: 9, value: 'rickOwens', label: 'Rick Owens'},
            {id: 9, value: 'other', label: 'other'},
        ]},
];
